### PR TITLE
added a camera that fixes the y coordinate when jumping, addressing Issue #47

### LINKED ISSUE #47: Stop camera from jumping up w/ Steve

### PR DESCRIPTION
**Pull request by jreeee**
fixes #47

### CODE REVIEW

File: Assets/Player/script/stevecontroller.cs [hunk 1]
```diff
@@ -131,6 +137,7 @@ public class stevecontroller : MonoBehaviour {
     private void FixedUpdate() {
         //Ground_check();
         Move(horizontal_move * Time.fixedDeltaTime);
+        Debug.Log(m_cam.position.x + " " + m_cam.position.y + "\n");
```
Comment (jakobbbb) [inline Assets/Player/script/stevecontroller.cs:140]: that's annoying!!!!!!!!!
